networks:
  gitea:
    external: false

volumes:
  gitea:
    driver: local
  postgres:
    driver: local

services:
  webhook:
    build: .
    restart: always
    environment:
      - RUST_LOG=info
      - GITEA_AUTHORIZATION=Bearer Eq55NZMpMGPpQkfu
      - GITEA_BASE_URL=http://127.0.0.1:5541
      - GITEA_TOKEN=b81982c7a6351980513120ebbbee67d5218fe710
      - AI_BASE_URL=https://api.deepseek.com/v1
      - AI_KEY=sk-4a5b009d17ac42a397b911b11169477b
      - AI_MODEL=deepseek-chat
    networks:
      - gitea

  gitea:
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    networks:
      - gitea
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5541:3000"
      - "2222:22"
    depends_on:
      - db
      - webhook

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - postgres:/var/lib/postgresql
